### ISSUE TITLE
Not compatible with multiprocess - FF 52+

### ISSUE THREAD

**Issue by manu-p** [jaywink/diaspora-advanced-sharer#10]
Hi,

As of version 49, Firefox introduced the multiprocess feature.

This feature appears to be unactivated on my session due to the diaspora-advanced-sharer module not being compatible with multiprocess.

This Mozilla [compatibility reporter add-on](https://addons.mozilla.org/fr/firefox/addon/add-on-compatibility-reporter/) was used to find it out.

Hope you can do something to sort it out soon! Thanks!

**Comment by jaywink** [comment]
This add-on is basically legacy and will not be updated. The new Firefox requires rewriting add-on's as WebExtensions anyway, so the problem is larger.

I recommend using the native Firefox share feature, which has integration to the diaspora sharing service, if on FF56 or below. If on FF57 or above, [this extension](https://addons.mozilla.org/en-US/firefox/addon/share-backported/) backports the share feature which was removed in FF57.

It basically does the same thing as this add-on did.

Thanks for reporting anyway! Hope those help.
